#!/usr/bin/env bash
#region Get music directory defined in the bash variables
  . ~/.bash/Config/variables 
  IFS=$'\n\t'

  path="$music_dir/Metal"
#endregion

#region Building arrays from directories
dir_arr() {
  shopt -s nullglob
  local __resultvar=$1
  local dirPath=$1
  local dirs=()
  # Display names instead of dir paths
  #for dir in "${!dirs[@]}"; do
  for dir in "${dirPath[@]}"/*/;do 
    #dirs[$dir]=$(basename "${dirs[$dir]}")
    dirs+=( "$(basename "${dir%/}")" )
  done
  # Return array of dirs based on given arguments
  printf -v "$__resultvar" '%s' "${dirs[$dir]}"
  shopt -u nullglob
}
#endregion

#region Dynamic Selection 
select_from_list() {
  local __resultvar=$1
  local prompt="$2"
  shift 2
  local options=("$@") # Expand received arguments

  local old_prompt=$PS3
  PS3="$prompt "

  select opt in "${options[@]}"; do
    # Choose by number
    if [[ -n $opt ]]; then
      printf -v "$__resultvar" '%s' "$opt" # Return user choice as a variable
      PS3=$old_prompt # Reset prompt after choice
      return 0
    else 
      echo "Invalid selection"
    fi
  done
}
#endregion

# Start vlc for playback and read for keyboard interrupt
play_album() {
  local artist=$1
  local album=$2

  # Map tracks into an array
  mapfile -t tracks < <(find "$album" -maxdepth 1 -type f \
    \( -iname '*.mp3' -o -iname '*.flac' -o -iname '*.ogg' -o -iname '*.wav' \) | sort)

    trackCount=${#tracks[@]} # Counting tracks from array

  # Start vlc without interface
  nohup cvlc --play-and-exit "${tracks[@]}" >/dev/null 2>&1 &
    VLC_PID=$!

  clear && printf "Playing \e[1;4;31m%s\e[0m - \e[1;4;31m%s\e[0;37m
    Track Count: %d 
    VLC PID=%d
    Press enter to interrupt playback\n" \
    "$(basename "$artist")" "$(basename "$album")" "$trackCount" "$VLC_PID"
  #echo "${tracks[@]}"
  # Run read in the background
  read -r < /dev/tty &
  READ_PID=$!

  #region Exit normally or by interrupting
    # Wait for either VLC exit or enter input
      wait -n "$VLC_PID" "$READ_PID"

    # Check which one finished
    if kill -0 "$VLC_PID" 2>/dev/null; then
      # User pressed enter first - VLC still running
      printf "Stopping playback... \n"
      kill "$VLC_PID"
      wait "$VLC_PID" 2>/dev/null
    else
      # VLC finished playback normally
      printf "Album finished \n"
    fi

    # Cleanup
      kill "$READ_PID" 2>/dev/null
      wait "$READ_PID" 2>/dev/null
  #endregion
}

#region Artist selection
shopt -s nullglob
artists=()
  # Display names instead of dir paths
  #for dir in "${!dirs[@]}"; do
  for artist in "$path"/*/; do 
    artists+=( "$(basename "${artist}")" )
  done
shopt -u nullglob

select_from_list artistChoice "Artist number or name: >" "${artists[@]}"
#endregion

#echo "Selected artist: $artistChoice"

#region Album selection
shopt -s nullglob
albums=()
  # Create an array of names instead of dir paths
  for album in "$path/$artistChoice"/*/; do 
    albums+=( "$(basename "${album%/}")" )
  done
shopt -u nullglob

select_from_list albumChoice "Album number or name: >" "${albums[@]}"

play_album "$artistChoice" "$path/$artistChoice/$albumChoice"
#endregion